name: Webpack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          npm install
          npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update webpack assets
          file_pattern: docs/assets/css/*.css docs/assets/js/*.js
